# Generated by Django 5.0.7 on 2024-08-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='d', max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('quantity_in_stock', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
            ],
        ),
    ]
